project_path:
  class: Directory
  path: ./
data_path:
  class: Directory
  path: ./data
param_path:
  class: Directory
  path: ./param
results_path:
  class: Directory
  path: ./results
targets:
  class: File
  path: targets.txt
Rmd:
  class: File
  path: new.Rmd
